title: "My Project: A Guide"
#description: "A showcase of my projects and work."

# Social links
social:
  github: Alfred Papa
  linkedin: Alfred Papa
  url: https://www.linkedin.com/in/alfred-papa-0028b0172/

theme: minima
