title: "My Portfolio"
#description: "A showcase of my projects and work."

# Social links
social: https://www.linkedin.com/in/alfred-papa-0028b0172/
  github: Alfred Papa
  linkedin: Alfred Papa
  
theme: jekyll-theme-minimal
